spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.lock-retry-count=50

# ─── Logger ───────────────────────────────────────────────────────
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE