CREATE TABLE usuario_domus_admin (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE igreja ADD COLUMN status_tenant VARCHAR(20) NOT NULL DEFAULT 'ATIVO';
ALTER TABLE igreja ADD COLUMN motivo_suspensao VARCHAR(255);
