-- V55: Garante todas as colunas de conta_a_pagar e pagamento_conta no Neon DB
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS beneficiario_pessoa_id UUID REFERENCES pessoa(id);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS beneficiario_texto VARCHAR(120);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS descricao VARCHAR(255);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS competencia DATE;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS linha_digitavel VARCHAR(80);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS documento_numero VARCHAR(40);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS cnpj_beneficiario VARCHAR(20);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS valor NUMERIC(15,2);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS vencimento DATE;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'EM_ABERTO';
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS valor_pago NUMERIC(15,2) DEFAULT 0;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS pago_em DATE;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS serie_id UUID REFERENCES conta_a_pagar(id);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS diverge_da_serie BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS recorrencia_frequencia VARCHAR(20);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS recorrencia_ate DATE;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS recorrencia_vezes INT;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS recorrencia_dia_ancora INT;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS anexo_id UUID;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS criado_por_usuario_id UUID REFERENCES usuario(id);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS criado_por_texto VARCHAR(255);
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE conta_a_pagar ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS valor_pago NUMERIC(15,2);
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS juros_acrescimos NUMERIC(15,2) DEFAULT 0;
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS desconto NUMERIC(15,2) DEFAULT 0;
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS pago_em DATE;
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS forma VARCHAR(50);
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS anexo_id UUID;
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS estornado BOOLEAN DEFAULT false;
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS estornado_em TIMESTAMP;
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS estornado_por_usuario_id UUID REFERENCES usuario(id);
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS criado_por_usuario_id UUID REFERENCES usuario(id);
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE pagamento_conta ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;